/**
 * MiniLang Lexer — generated by pyreez (openai/gpt-4.1-mini).
 * Tokenizes source code string into Token[].
 */

import { TokenType, type Token, KEYWORDS } from "./tokens";

export class Lexer {
  private source: string;
  private pos: number = 0;
  private line: number = 1;
  private column: number = 1;

  constructor(source: string) {
    this.source = source;
  }

  public tokenize(): Token[] {
    const tokens: Token[] = [];
    while (!this.isAtEnd()) {
      this.skipWhitespace();
      if (this.isAtEnd()) break;
      const token = this.nextToken();
      tokens.push(token);
    }
    tokens.push({
      type: TokenType.EOF,
      value: "",
      line: this.line,
      column: this.column,
    });
    return tokens;
  }

  private nextToken(): Token {
    const char = this.peek();

    if (this.isAlpha(char) || char === "_") {
      return this.identifierOrKeyword();
    }

    if (this.isDigit(char)) {
      return this.number();
    }

    if (char === '"') {
      return this.string();
    }

    return this.operatorOrPunctuation();
  }

  private identifierOrKeyword(): Token {
    const startLine = this.line;
    const startColumn = this.column;
    let value = "";

    while (
      !this.isAtEnd() &&
      (this.isAlphaNumeric(this.peek()) || this.peek() === "_")
    ) {
      value += this.advance();
    }

    const type = KEYWORDS[value] ?? TokenType.IDENT;

    return { type, value, line: startLine, column: startColumn };
  }

  private number(): Token {
    const startLine = this.line;
    const startColumn = this.column;
    let value = "";
    let isFloat = false;

    while (!this.isAtEnd() && this.isDigit(this.peek())) {
      value += this.advance();
    }

    if (!this.isAtEnd() && this.peek() === ".") {
      if (this.isDigit(this.peekNext())) {
        isFloat = true;
        value += this.advance();
        while (!this.isAtEnd() && this.isDigit(this.peek())) {
          value += this.advance();
        }
      }
    }

    return {
      type: isFloat ? TokenType.FLOAT : TokenType.INT,
      value,
      line: startLine,
      column: startColumn,
    };
  }

  private string(): Token {
    const startLine = this.line;
    const startColumn = this.column;
    let value = "";
    this.advance(); // consume opening "

    while (!this.isAtEnd()) {
      const c = this.advance();
      if (c === '"') {
        return {
          type: TokenType.STRING,
          value,
          line: startLine,
          column: startColumn,
        };
      } else if (c === "\\") {
        if (this.isAtEnd()) {
          this.error("Unterminated string (escape at EOL)");
        }
        const nextChar = this.advance();
        switch (nextChar) {
          case '"':
            value += '"';
            break;
          case "\\":
            value += "\\";
            break;
          case "n":
            value += "\n";
            break;
          case "r":
            value += "\r";
            break;
          case "t":
            value += "\t";
            break;
          case "0":
            value += "\0";
            break;
          default:
            this.error(`Unknown escape sequence: \\${nextChar}`);
        }
      } else if (c === "\n") {
        this.error("Unterminated string literal at newline");
      } else {
        value += c;
      }
    }

    this.error("Unterminated string literal");
  }

  private operatorOrPunctuation(): Token {
    const startLine = this.line;
    const startColumn = this.column;
    const c = this.advance();

    switch (c) {
      case "+":
        return { type: TokenType.PLUS, value: c, line: startLine, column: startColumn };
      case "-":
        return { type: TokenType.MINUS, value: c, line: startLine, column: startColumn };
      case "*":
        return { type: TokenType.STAR, value: c, line: startLine, column: startColumn };
      case "/":
        return { type: TokenType.SLASH, value: c, line: startLine, column: startColumn };
      case "%":
        return { type: TokenType.PERCENT, value: c, line: startLine, column: startColumn };
      case ";":
        return { type: TokenType.SEMICOLON, value: c, line: startLine, column: startColumn };
      case ",":
        return { type: TokenType.COMMA, value: c, line: startLine, column: startColumn };
      case "(":
        return { type: TokenType.LPAREN, value: c, line: startLine, column: startColumn };
      case ")":
        return { type: TokenType.RPAREN, value: c, line: startLine, column: startColumn };
      case "{":
        return { type: TokenType.LBRACE, value: c, line: startLine, column: startColumn };
      case "}":
        return { type: TokenType.RBRACE, value: c, line: startLine, column: startColumn };
      case "=":
        if (this.match("=")) {
          return { type: TokenType.EQ, value: "==", line: startLine, column: startColumn };
        }
        return { type: TokenType.ASSIGN, value: "=", line: startLine, column: startColumn };
      case "!":
        if (this.match("=")) {
          return { type: TokenType.NEQ, value: "!=", line: startLine, column: startColumn };
        }
        return { type: TokenType.NOT, value: "!", line: startLine, column: startColumn };
      case "<":
        if (this.match("=")) {
          return { type: TokenType.LTE, value: "<=", line: startLine, column: startColumn };
        }
        return { type: TokenType.LT, value: "<", line: startLine, column: startColumn };
      case ">":
        if (this.match("=")) {
          return { type: TokenType.GTE, value: ">=", line: startLine, column: startColumn };
        }
        return { type: TokenType.GT, value: ">", line: startLine, column: startColumn };
    }

    this.error(`Unexpected character '${c}'`);
  }

  private skipWhitespace(): void {
    while (!this.isAtEnd()) {
      const c = this.peek();
      if (c === " " || c === "\r" || c === "\t") {
        this.advance();
      } else if (c === "\n") {
        this.advance();
        this.line++;
        this.column = 1;
      } else if (c === "/" && this.peekNext() === "/") {
        // Line comment: skip to end of line
        while (!this.isAtEnd() && this.peek() !== "\n") {
          this.advance();
        }
      } else {
        break;
      }
    }
  }

  private isAtEnd(): boolean {
    return this.pos >= this.source.length;
  }

  private peek(): string {
    if (this.isAtEnd()) return "\0";
    return this.source[this.pos];
  }

  private peekNext(): string {
    if (this.pos + 1 >= this.source.length) return "\0";
    return this.source[this.pos + 1];
  }

  private advance(): string {
    const c = this.source[this.pos];
    this.pos++;
    this.column++;
    return c;
  }

  private match(expected: string): boolean {
    if (this.isAtEnd()) return false;
    if (this.source[this.pos] !== expected) return false;
    this.pos++;
    this.column++;
    return true;
  }

  private isAlpha(c: string): boolean {
    return /^[A-Za-z]$/.test(c);
  }

  private isDigit(c: string): boolean {
    return /^[0-9]$/.test(c);
  }

  private isAlphaNumeric(c: string): boolean {
    return this.isAlpha(c) || this.isDigit(c);
  }

  private error(message: string): never {
    throw new Error(`Lexer Error [${this.line}:${this.column}]: ${message}`);
  }
}
