/**
 * MiniLang Token Types — generated by pyreez (openai/gpt-4.1-nano).
 */

export enum TokenType {
  // Keywords
  LET,
  MUT,
  IF,
  ELSE,
  WHILE,
  FN,
  AND,
  OR,
  NOT,
  TRUE,
  FALSE,
  NULL_KW,
  RETURN,
  // Literals
  INT,
  FLOAT,
  STRING,
  // Identifiers
  IDENT,
  // Operators
  PLUS,
  MINUS,
  STAR,
  SLASH,
  PERCENT,
  EQ,
  NEQ,
  LT,
  LTE,
  GT,
  GTE,
  ASSIGN,
  // Punctuation
  SEMICOLON,
  COMMA,
  LPAREN,
  RPAREN,
  LBRACE,
  RBRACE,
  // Built-in functions
  PRINT,
  LEN,
  TYPE,
  EOF,
}

export interface Token {
  type: TokenType;
  value: string;
  line: number;
  column: number;
}

export const KEYWORDS: Record<string, TokenType> = {
  let: TokenType.LET,
  mut: TokenType.MUT,
  if: TokenType.IF,
  else: TokenType.ELSE,
  while: TokenType.WHILE,
  fn: TokenType.FN,
  and: TokenType.AND,
  or: TokenType.OR,
  not: TokenType.NOT,
  true: TokenType.TRUE,
  false: TokenType.FALSE,
  null: TokenType.NULL_KW,
  return: TokenType.RETURN,
  print: TokenType.PRINT,
  len: TokenType.LEN,
  type: TokenType.TYPE,
};
